# Importa a bibloteca pandas

In [2]:
import pandas as pd

#  Carregar osdados

In [17]:
df = pd.read_csv('dados_climaticos_ficticios.csv')

# Explorar funçãoes do DataFrame do pandas

In [18]:
# Vizualiza dados no topo do datafram
df.head()

    Ano  CO2_ppm  Temp_Anomalia_C Evento_Extremo
0  1950   304.55             0.20            Sim
1  1951   312.17             0.06            Não
2  1952   310.58            -0.05            Não
3  1953   312.82            -0.10            Não
4  1954   315.65            -0.18            Não

In [19]:
# Vizualiza dados na base do dataframe]
df.tail()

     Ano  CO2_ppm  Temp_Anomalia_C Evento_Extremo
69  2019   414.88             1.09            Não
70  2020   418.19             1.32            Não
71  2021   415.93             0.89            Sim
72  2022   416.42             1.28            Não
73  2023   419.48             1.00            Não

# Dicinario de dados

- ano: ano de registro da informação
- co2ppm: concentração e particula por milhão de CO2 na atmosfera
- temp_anomalia_c: variação ou diferença da temperatura media no ano com a temperatura media historicam em graus celsios
- evento_extremo: ondicação categorica Sim/Não de ocorrencia d evento extremo no ano

In [20]:
# Resumo da extrutura do dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Ano              74 non-null     int64
 1   CO2_ppm          74 non-null     float64
 2   Temp_Anomalia_C  74 non-null     float64
 3   Evento_Extremo   74 non-null     object
dtypes: float64(2), int64(1), object(1)
memory usage: 2.4+ KB

In [22]:
# Descrição estatistica da base
df.describe()

               Ano     CO2_ppm  Temp_Anomalia_C
count    74.000000   74.000000        74.000000
mean   1986.500000  365.221486         0.555811
std      21.505813   32.768101         0.367379
min    1950.000000  304.550000        -0.180000
25%    1968.250000  336.907500         0.272500
50%    1986.500000  366.810000         0.545000
75%    2004.750000  392.395000         0.855000
max    2023.000000  419.480000         1.400000

# Separar a base de dados em 3 de acordo ao ano do registro
- Menor que 1975
- Maior ou igual a 1975 e menor que 2000
- Maior ou igual a 2000

In [44]:
df_p1 = df[df["Ano"] < 1975]
df_p2 = df[((df["Ano"] >= 1975) & (df["Ano"] < 2000))]
df_p3 = df[df["Ano"] >= 2000]

In [41]:
df_p1.describe()

               Ano     CO2_ppm  Temp_Anomalia_C
count    25.000000   25.000000        25.000000
mean   1962.000000  328.019600         0.168400
std       7.359801   12.195995         0.182521
min    1950.000000  304.550000        -0.180000
25%    1956.000000  317.460000         0.060000
50%    1962.000000  327.030000         0.190000
75%    1968.000000  336.760000         0.280000
max    1974.000000  349.300000         0.480000

In [42]:
df_p2.describe()

               Ano     CO2_ppm  Temp_Anomalia_C
count    25.000000   25.000000        25.000000
mean   1987.000000  366.024400         0.573600
std       7.359801   11.487436         0.180182
min    1975.000000  346.630000         0.270000
25%    1981.000000  356.110000         0.440000
50%    1987.000000  367.270000         0.550000
75%    1993.000000  374.970000         0.660000
max    1999.000000  385.860000         1.000000

In [45]:
df_p3.describe()

               Ano     CO2_ppm  Temp_Anomalia_C
count    24.000000   24.000000        24.000000
mean   2011.500000  403.137083         0.940833
std       7.071068   10.485825         0.203874
min    2000.000000  387.270000         0.570000
25%    2005.750000  393.152500         0.805000
50%    2011.500000  403.340000         0.925000
75%    2017.250000  411.707500         1.017500
max    2023.000000  419.480000         1.400000